# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.1.6
_src_path: https://github.com/OCA/oca-addons-repo-template.git
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: true
odoo_version: 14.0
rebel_module_groups:
- account_recalculate_stock_move
repo_description: Odoo Bulagaia locales.
repo_name: Bulgarian locales
repo_slug: l10n-bulgaria
travis_apt_packages:
- docker
- nano
travis_apt_sources: []
