<?xml version="1.0" encoding="WINDOWS-1251"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="etzemploy">
		<xs:annotation>
			<xs:documentation>Електронен трудов запис за сключване, изменение и прекратяване на трудов договор и за възникване, промяна и прекратяване на служебно правоотношение</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="eik" type="bulstat">
					<xs:annotation>
						<xs:documentation>4. ЕИК на работодателя / органа по назначаването</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="contract">
					<xs:annotation>
						<xs:documentation>електронен трудов запис</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rowenum" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="employtype">
											<xs:annotation>
												<xs:documentation>1. Вид правоотношение:
01 – за трудово правоотношение;
02 – за служебно правоотношение.</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:enumeration value="01"/>
													<xs:enumeration value="02"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="codecorrection">
											<xs:annotation>
												<xs:documentation>2. Код корекция</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:enumeration value="0"/>
													<xs:enumeration value="1"/>
													<xs:enumeration value="2"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="documenttype">
											<xs:annotation>
												<xs:documentation>3. Тип на документа</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:enumeration value="0"/>
													<xs:enumeration value="1"/>
													<xs:enumeration value="2"/>
													<xs:enumeration value="3"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="egn" type="egn">
											<xs:annotation>
												<xs:documentation>5. ЕГН (ЛН, ЛНЧ), служебен номер от НАП</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="egntype" type="egntype">
											<xs:annotation>
												<xs:documentation>6. Код за ЕГН /ЛН, ЛНЧ/       Сл. номер от НАП :
0 – ако лицето е с единен граждански номер, 
2 – ако лицето е с личен номер на чужденец, личен номер или служебен номер, издаден от НАП.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="firstname">
											<xs:annotation>
												<xs:documentation>7.Име</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="200"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="secondname" minOccurs="0">
											<xs:annotation>
												<xs:documentation>8.Презиме</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="200"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="thirdname">
											<xs:annotation>
												<xs:documentation>9.Фамилия</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="200"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="contractdate" type="xs:date">
											<xs:annotation>
												<xs:documentation>10. Дата на сключване на трудовия договор или на издаване на акта за назначаване</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="contractno" minOccurs="0">
											<xs:annotation>
												<xs:documentation>11. Номер на акта за назначаване</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="200"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="contracttype">
											<xs:annotation>
												<xs:documentation>12. Основание на трудовия договор/акта за назначаване или основание за промяна на правоотношението</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
													<xs:pattern value="[0-9]{3,3}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="emploeerank" minOccurs="0">
											<xs:annotation>
												<xs:documentation>13. Ранг на държавния служител     (дипломатически ранг)</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
													<xs:pattern value="[0-9]{3,3}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="begindate" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>14. Дата на начало на изпълнение на трудовия договор или на възникване на служебното правоотношение</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="termdate" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>15. Срок на трудовия договор (на допълнителното споразумение) или на акта за назначаване</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="changedate" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>16. Дата на сключване на допълнително споразумение или на издаване на акта за промяна на служебното правоотношение </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="entrydate" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>16A.Дата на влизане в сила на изменението на трудовото или служебното правоотношение</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="changeno" minOccurs="0">
											<xs:annotation>
												<xs:documentation>17. Номер на акта за промяна на служебното правоотношение</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="200"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="salary" type="xs:float" minOccurs="0">
											<xs:annotation>
												<xs:documentation>18. Размер на основното трудово възнаграждение или на основната месечна заплата</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="codenkpd" minOccurs="0">
											<xs:annotation>
												<xs:documentation>19. Код по НКПД </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="8"/>
													<xs:pattern value="[0-9]{8,8}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="codeposition" minOccurs="0">
											<xs:annotation>
												<xs:documentation>20. Код на заеманата длъжност от държавния служител</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="12"/>
													<xs:pattern value="[0-9]{12,12}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="codekid" minOccurs="0">
											<xs:annotation>
												<xs:documentation>21. Код по КИД  </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="4"/>
													<xs:pattern value="[0-9]{4,4}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="codeekatte" minOccurs="0">
											<xs:annotation>
												<xs:documentation>22. Код по ЕКАТТЕ  </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="5"/>
													<xs:pattern value="[0-9]{5,5}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="codehours" type="xs:positiveInteger" minOccurs="0">
											<xs:annotation>
												<xs:documentation>23. Код за работно време  </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="workinghours" type="xs:positiveInteger" minOccurs="0">
											<xs:annotation>
												<xs:documentation>23А. Продължителност на работното време  </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="vacationdays" type="xs:positiveInteger" minOccurs="0">
											<xs:annotation>
												<xs:documentation>24. Дни уговорен платен годишен отпуск по трудово правоотношение </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="usedvacation" type="xs:integer" minOccurs="0">
											<xs:annotation>
												<xs:documentation>25. Дни използван платен годишен отпуск, полагащ се за годината на прекратяване на трудовото правоотношение  </xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="enddate" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>26. Дата на прекратяване на правоотношението</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="endreason" minOccurs="0">
											<xs:annotation>
												<xs:documentation>27. Основание за прекратяване</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="3"/>
													<xs:pattern value="[0-9]{3,3}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="compensation222" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>28.Изплатено обезщетение по чл. 222, ал. 2 от КТ при прекратяване на трудовия договор</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="compensation106" type="xs:date" minOccurs="0">
											<xs:annotation>
												<xs:documentation>29. Изплатено обезщетение по чл. 222, ал. 3 КТ при прекратяване на трудовия договор или по чл. 106, ал. 3 ЗДСл при прекратяване на служебното правоотношение</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="experience" minOccurs="0">
											<xs:annotation>
												<xs:documentation>30. Продължителност на времето, което се признава за трудов стаж</xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="6"/>
													<xs:pattern value="[0-9]{6,6}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="noexperience" minOccurs="0">
											<xs:annotation>
												<xs:documentation>31. Продължителност на времето, което не се признава за трудов стаж </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="6"/>
													<xs:pattern value="[0-9]{6,6}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="workperiod" minOccurs="0">
											<xs:annotation>
												<xs:documentation>32. Продължителност на времето, което се признава за служебен стаж или за стаж в дипломатическа служба </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:maxLength value="6"/>
													<xs:pattern value="[0-9]{6,6}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="commcode" minOccurs="0">
											<xs:annotation>
												<xs:documentation>33. Запорни съобщения по чл. 512, ал. 5 ГПК  </xs:documentation>
											</xs:annotation>
											<xs:simpleType>
												<xs:restriction base="xs:integer">
													<xs:totalDigits value="1"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:all>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="egn">
		<xs:restriction base="xs:string">
			<xs:length value="10"/>
			<xs:pattern value="[0-9]{10,10}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="bulstat">
		<xs:restriction base="xs:string">
			<xs:maxLength value="13"/>
			<xs:pattern value="[0-9]{1,13}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="egntype">
		<xs:annotation>
			<xs:documentation>0 – ако лицето е с единен граждански номер, или 2 – ако лицето е с личен номер на чужденец, личен номер или служебен номер, издаден от НАП</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:integer">
			<xs:enumeration value="0"/>
			<xs:enumeration value="2"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
