# -*- coding: utf-8 -*-
import base64
import logging
from datetime import date

from odoo import api, fields, models, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class L10nBgNraFileArchive(models.Model):
    """Неизменим номериран архив на генерираните НАП/НОИ файлове.

    Всеки генериран файл (TXT за Д1/Д6, XML за ЕТЗ/spr73) се вписва тук като
    immutable номериран запис — одитна следа „какво/кога/от кого генерирано".
    Номерът (NRAF/ГГГГ/NNNNN, годишен reset) идва през core ``sequence.mixin``,
    както регистрите — БЕЗ отделен ``ir.sequence`` запис.
    """

    _name = "l10n_bg.nra.file.archive"
    _description = "NRA/NSSI Generated File Archive"
    _inherit = ["mail.thread", "sequence.mixin"]
    _order = "file_date desc, id desc"
    _check_company_auto = True

    # -- sequence.mixin hooks (годишен поток, mirror на hr.leave.bg.register.mixin)
    _sequence_field = "name"
    _sequence_date_field = "file_date"
    _l10n_bg_file_prefix = "NRAF"

    name = fields.Char(
        string="Number",
        required=True,
        readonly=True,
        copy=False,
        default="/",
        index=True,
        tracking=True,
    )
    file_date = fields.Date(
        string="File Date",
        required=True,
        readonly=True,
        default=fields.Date.context_today,
        help="Date driving the yearly numbering sequence (generation date).",
    )
    declaration_id = fields.Many2one(
        comodel_name="nra.declaration",
        string="Source Declaration",
        ondelete="set null",
        readonly=True,
        help="Declaration the file was generated from. Soft link — the archive "
        "record survives if the declaration is later deleted.",
    )
    declaration_type = fields.Char(
        string="Declaration Type",
        readonly=True,
        help="Technical code of the declaration type at generation time "
        "(dec1, dec6, etz, spr73, ...).",
    )
    company_id = fields.Many2one(
        comodel_name="res.company",
        string="Company",
        required=True,
        readonly=True,
        default=lambda self: self.env.company,
    )
    period_year = fields.Char(string="Year", size=4, readonly=True)
    period_month = fields.Selection(
        selection=[
            ("1", "January"), ("2", "February"), ("3", "March"),
            ("4", "April"), ("5", "May"), ("6", "June"),
            ("7", "July"), ("8", "August"), ("9", "September"),
            ("10", "October"), ("11", "November"), ("12", "December"),
        ],
        string="Month",
        readonly=True,
    )
    file_format = fields.Selection(
        selection=[("txt", "TXT"), ("xml", "XML"), ("docx", "DOCX")],
        string="File Format",
        required=True,
        readonly=True,
        default="txt",
    )
    file_content = fields.Binary(
        string="File Content",
        attachment=True,
        readonly=True,
        copy=False,
        help="Immutable raw file bytes as generated.",
    )
    file_name = fields.Char(string="Filename", readonly=True, copy=False)
    file_size = fields.Integer(
        string="File Size (bytes)",
        compute="_compute_file_size",
        store=True,
    )
    generated_at = fields.Datetime(
        string="Generated At",
        readonly=True,
        default=fields.Datetime.now,
    )
    generated_by = fields.Many2one(
        comodel_name="res.users",
        string="Generated By",
        readonly=True,
        default=lambda self: self.env.user,
    )
    note = fields.Text(string="Note")

    # ------------------------------------------------------------------
    # Compute
    # ------------------------------------------------------------------
    @api.depends("file_content")
    def _compute_file_size(self):
        for rec in self:
            # file_content е base64-encoded; декодираме за реалния размер в байтове.
            rec.file_size = len(base64.b64decode(rec.file_content)) if rec.file_content else 0

    # ------------------------------------------------------------------
    # Sequence (годишен NRAF/ГГГГ/NNNNN през sequence.mixin — mirror на регистрите)
    # ------------------------------------------------------------------
    def _get_starting_sequence(self):
        """Seed ``NRAF/ГГГГ/00000`` → разпознава се като годишен поток."""
        self.ensure_one()
        ref = fields.Date.to_date(self.file_date) or fields.Date.context_today(self)
        return "%s/%s/00000" % (self._l10n_bg_file_prefix, ref.year)

    def _get_last_sequence_domain(self, relaxed=False):
        """Годишно скоупване по ``file_date`` (както ``account.move``)."""
        self.ensure_one()
        where_string = "WHERE name NOT IN ('/', '')"
        param = {}
        if not relaxed:
            ref = fields.Date.to_date(self.file_date) or fields.Date.context_today(self)
            where_string += " AND file_date BETWEEN %(date_start)s AND %(date_end)s"
            param["date_start"] = date(ref.year, 1, 1)
            param["date_end"] = date(ref.year, 12, 31)
            # Изключваме месечните формати — ние сме годишни.
            param["anti_regex"] = self._make_regex_non_capturing(
                self._sequence_monthly_regex.split("(?P<seq>")[0]) + "$"
            where_string += " AND sequence_prefix !~ %(anti_regex)s "
        return where_string, param

    # ------------------------------------------------------------------
    # Numbering + immutability
    # ------------------------------------------------------------------
    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for rec in records:
            if not rec.name or rec.name == "/":
                # context flag → позволява на write() guard-а да пропусне
                # присвояването на номера при създаване.
                rec.with_context(l10n_bg_archive_init=True)._set_next_sequence()
        return records

    def write(self, vals):
        # Immutable архив: съдържанието/номерът/метаданните не се променят след
        # създаване (одитна цялост). Позволяваме само note + системни полета.
        protected = {
            "file_content", "file_name", "name", "declaration_type",
            "file_format", "period_year", "period_month", "company_id", "file_date",
        }
        if not self.env.context.get("l10n_bg_archive_init"):
            changed = protected.intersection(vals)
            if changed:
                raise UserError(
                    _("Archived NRA/NSSI files are immutable; cannot modify: %s")
                    % ", ".join(sorted(changed))
                )
        return super().write(vals)
