"""
Generic response table for non-fiscal IoT actions (scale / display /
scanner / pinpad-as-iot).

Why a separate table from `fiscal.printer.response`:

  * `fiscal.printer.response` was designed around a fiscal printer's
    response shape — header/messages/serial/etc. Reusing it for a 1.234
    kg scale reading or a customer-display ack would conflate two
    unrelated lifecycles, and any future schema change would risk the
    legacy fiscal flow.
  * The legacy fiscal flow is left untouched: same model, same fields,
    same RPC paths. New IoT flows write into `iot.device.response` only.

Lifecycle (mirrors fiscal.printer.response):

    1. Server-side code calls `iot.device.action_via_proxy(...)` which
       generates a request_id, sends a `bus.bus` message, and starts
       polling THIS table for the matching `request_id`.
    2. Browser receives the bus message, fetches the IoT Box URL on
       behalf of the server, and writes the result into a new
       `iot.device.response` row.
    3. Server poller picks up the row, returns the data, and unlinks
       the row immediately.

Records are short-lived (seconds, not minutes). A daily cron deletes
any orphans older than 1 day defensively.
"""

from datetime import timedelta

from odoo import api, fields, models


class IotDeviceResponse(models.Model):
    _name = "iot.device.response"
    _description = "IoT device response (browser-proxied action result)"
    _order = "create_date desc"

    request_id = fields.Char(
        string="Request ID",
        required=True,
        index=True,
        help="UUID generated by the server when sending the request to "
             "the browser via bus.bus. The browser writes the response "
             "with the same request_id so the polling server method can "
             "match it.",
    )
    iot_device_id = fields.Many2one(
        "iot.device",
        string="IoT Device",
        ondelete="cascade",
        index=True,
    )
    iot_box_id = fields.Many2one(
        "iot.box",
        string="IoT Box",
        related="iot_device_id.iot_id",
        store=True,
    )
    success = fields.Boolean(string="Success", default=False)
    data = fields.Text(
        string="Response Data (JSON)",
        help="Raw JSON-encoded response from the IoT Box. Caller "
             "deserialises with `json.loads()`.",
    )
    error_message = fields.Text(string="Error Message")

    def get_data(self):
        """Decode `data` to a dict; returns {} if empty/invalid."""
        import json
        self.ensure_one()
        if not self.data:
            return {}
        try:
            return json.loads(self.data)
        except (ValueError, TypeError):
            return {}

    @api.model
    def _gc_old_responses(self):
        """Drop any response older than 1 day — defensive cleanup for
        rows the polling server somehow failed to consume (e.g. server
        crashed mid-poll). Called from the daily ir.cron."""
        cutoff = fields.Datetime.now() - timedelta(days=1)
        old = self.search([("create_date", "<", cutoff)])
        if old:
            old.unlink()
        return True
